### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by TamsynUlthara** [joe42/CloudFusion#27]
Is CloudFusion open source?

There's no mention in the `README.rst`, nor a `LICENSE` / `COPYING` file, and I see this in the `setup.py` classifiers:

```
        "License :: Other/Proprietary License",
```

(And FWIW, this seems to be the case for most of your other projects on GItHub, e.g., `mangafuse`.)

**Comment by joe42** [comment]
You may use CloudFusion under the GNU GPL. If you need another license, please let me know. I'm not charging anything, but if CloudFusion gets to be part of another (commercial) software I would be interested what project it is used in.

**Comment by TamsynUlthara** [comment]
Glad to hear it's open source!

If you prefer the GNU GPL, it would be really helpful to add a GPL `COPYING` file (of whichever version of the GPL you choose) along with updating the `setup.py` with whatever classifier matches that version.

Here's links to the [GPL v2](https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt) and [GPL v3](http://www.gnu.org/licenses/gpl-3.0.txt) that you can drop in as `COPYING`.

Here's the various GNU license classifiers:

```
License :: OSI Approved :: GNU Affero General Public License v3
License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)
License :: OSI Approved :: GNU Free Documentation License (FDL)
License :: OSI Approved :: GNU General Public License (GPL)
License :: OSI Approved :: GNU General Public License v2 (GPLv2)
License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)
License :: OSI Approved :: GNU General Public License v3 (GPLv3)
License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
License :: OSI Approved :: GNU Lesser General Public License v2 (LGPLv2)
License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)
License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)
License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)
License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)
```

You may also want to mention the license in your `README.rst`, e.g., for GPL v2 or later:

```
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
```
